name: Update repo's and AUR's PKGBUILD

on:
  push:
  schedule: 
    - cron:  '*/5 * * * *'
  workflow_dispatch:

jobs:
  update-repo:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    container: archlinux:latest
    steps:
      - name: install dependencies
        run: |
          pacman -Syyu --noconfirm
          pacman -S git binutils --noconfirm

      - name: checkout repo content
        uses: actions/checkout@v2

      - name: create user
        run: |
          useradd -m homlet

      - name: update PKGBUILD
        run: |
          git clone https://github.com/project-slippi/dolphin /tmp/dolphin
          cd /tmp/dolphin
          TAGNAME="$(git describe --tags --abbrev=0)"
          git checkout --quiet "$(git rev-list -n 1 $TAGNAME)"
          PKGVER="$(git describe --long --tags | sed -e 's/-\([^-]*-g[^-]*\)$/-r\1/' -e 's/-/./g')"
          cd -

          sed -i "/^tag=/c\tag=\'$TAGNAME\'" ./PKGBUILD
          sed -i "/^pkgver=/c\pkgver=\'$PKGVER\'" ./PKGBUILD

          sed -i "/^Version=/c\Version=\'$PKGVER\'" ./slippi-mainline.desktop

          chown -R homlet:homlet .
          su -c "makepkg --printsrcinfo > .SRCINFO" homlet
          chown -R root:root .

      - name: push changes to repo
        run: |
          git config --global user.name 'HamletDuFromage'
          git config --global user.email '61667930+HamletDuFromage@users.noreply.github.com'
          git add PKGBUILD .SRCINFO slippi-mainline.desktop
          if [[ `git status --porcelain` ]]; then
            git commit -m "automatic: updated PKGBUILD (repo)"
            git push
          else
            echo "Nothing to commit! (repo)"
          fi

  update-aur:
    needs: update-repo
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo content
        uses: actions/checkout@v2

      - name: Setup SSH Keys and known_hosts
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan aur.archlinux.org >> ~/.ssh/known_hosts
          ssh-agent -a $SSH_AUTH_SOCK > /dev/null
          ssh-add - <<< "${{ secrets.AUR_SSH_PRIVATE_KEY }}"

      - name: push changes to aur
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: |
            git clone ssh://aur@aur.archlinux.org/slippi-mainline.git /tmp/aur
            cp PKGBUILD .SRCINFO slippi-mainline.svg slippi-mainline.desktop /tmp/aur/
            cd /tmp/aur
            git config --global user.name 'HamletDuFromage (github workflow https://github.com/HamletDuFromage/slippi-mainline-PKGBUILD)'
            git config --global user.email '61667930+HamletDuFromage@users.noreply.github.com'
            git add PKGBUILD .SRCINFO slippi-mainline.svg slippi-mainline.desktop
            if [[ `git status --porcelain` ]]; then
              git commit -m "automatic: updated PKGBUILD (AUR)"
              git push
            else
              echo "Nothing to commit! (AUR)"
            fi
